# Generated by Django 4.2.9 on 2024-04-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_fakemodel_delete_testmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeProxyModel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("myapp.fakemodel",),
        ),
    ]
